language: node_js
sudo: false
env:
  - PGUSER=postgres PGDATABASE=postgres

matrix:
  include:
    # Older ones are from brianc/node-postgres, so let's roll with that.
    - node_js: "0.10"
      addons:
        postgresql: "9.4"
    - node_js: "0.12"
      addons:
        postgresql: "9.4"
    - node_js: "4"
      addons:
        postgresql: "9.4"
    - node_js: "5"
      addons:
        postgresql: "9.4"

    # Test multiple Postgres versions for latest node.
    - node_js: "6"
      addons:
        postgresql: "9.1"
    - node_js: "6"
      addons:
        postgresql: "9.2"
    - node_js: "6"
      addons:
        postgresql: "9.3"
    - node_js: "6"
      addons:
        postgresql: "9.4"
